[package]
name = "poirot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "*"
colored = "*"
hashbrown = { version = "*", features = ["inline-more"] }
poirot-mutator = { path = "poirot-mutator" }
prettyplease = "*"
syn = { version = "*", features = ["extra-traits", "full"] }
