[package]
name = "poirot-mutator"
version = "0.1.0"
edition = "2021"
authors = ["Will Sturgeon <willstrgn@gmail.com>"]

[dependencies]
proc-macro2 = "*"
syn = { version = "*", features = ["extra-traits", "full"] }
quote = "*"

[lib]
proc-macro = true
