name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Expand
      run: # rustup toolchain install nightly && cargo install cargo-expand && cd test && cargo +nightly expand --verbose --color=always
    - name: Build
      run: cargo build --verbose --color=always
    - name: Check
      run: cargo check --verbose --color=always && cd sleuth-mutator && cargo check --verbose --color=always && cd ../test && cargo check --verbose --color=always
    - name: Clippy
      run: cargo clippy --verbose --color=always && cd sleuth-mutator && cargo clippy --verbose --color=always && cd ../test && cargo clippy --verbose --color=always
    - name: Test
      run: cargo test --verbose --color=always && cd sleuth-mutator && cargo test --verbose --color=always && cd ../test && cargo test --verbose --color=always
