name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: RUST_BACKTRACE=1 cargo build --verbose
    - name: Check
      run: RUST_BACKTRACE=1 cargo check --verbose && cd sleuth-mutator && cargo check --verbose && cd ../test && cargo check --verbose
    - name: Clippy
      run: RUST_BACKTRACE=1 cargo clippy --verbose && cd sleuth-mutator && cargo clippy --verbose && cd ../test && cargo clippy --verbose
    - name: Test
      run: RUST_BACKTRACE=1 cargo test --verbose && cd sleuth-mutator && cargo test --verbose && cd ../test && cargo test --verbose
